### ISSUE TITLE
[BE] 이슈 작성 시 내용 최대 글자 초과 시 예외 처리

### ISSUE THREAD

**Issue by sanhee** [ghojeong/issue-tracker#184]
```json
com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'content' at row 1
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:104) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1092) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1040) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1348) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1025) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61) ~[HikariCP-4.0.3.jar:na]
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java) ~[HikariCP-4.0.3.jar:na]
	at org.springframework.jdbc.core.JdbcTemplate.lambda$update$3(JdbcTemplate.java:992) ~[spring-jdbc-5.3.7.jar:5.3.7]
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:651) ~[spring-jdbc-5.3.7.jar:5.3.7]
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:991) ~[spring-jdbc-5.3.7.jar:5.3.7]
	at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.update(NamedParameterJdbcTemplate.java:356) ~[spring-jdbc-5.3.7.jar:5.3.7]
```

```json
{
    "timestamp": "2021-07-08T18:49:30.421+00:00",
    "status": 500,
    "error": "Internal Server Error",
    "path": "/api/web/issues"
}
```

**Comment by ghojeong** [comment]
상식적으로 content 는 텍스트 길이가 길게 작성되어야 할 텐데, 300 이 아니라 좀 크게 잡읍시다. 8192 라던가

**Comment by ghojeong** [comment]
6b48e713a72c65b0d54dcc6a759dd238ab65eb4a 커밋에서 긴급 업데이트했습니다.
말했다시피 오전 중에는 제가 좀 많이 바빠서 대응이 어렵습니다.
PR 을 해야하지만 생략을 하게 되었네요.
